### ISSUE TITLE
add '-Xss' option to avoid StackOverflowError

### ISSUE THREAD

**Issue by ybiquitous** [hiroaki-yamamoto/node-validator-nu#13]
Hi.

There is a tip in [Validator.nu](http://validator.github.io/validator/) site. The following:

```
Note: If you get a StackOverflowError error when using the vnu.jar file, try adjusting the thread stack size by providing the -Xss option to java:
    java -Xss512k -jar ~/vnu.jar FILE.html...
```

When passing many files, `StackOverflowError` caused, so I need a new option for passing `-Xss` option.

By all means thank you correspondence.

**Comment by hiroaki-yamamoto** [comment]
Hi :smiley: 
Instead I will add "param" flags

**Comment by ybiquitous** [comment]
I confirmed new feature about Java options in the latest version.

Very very thanks!
